### ISSUE TITLE
Retrieving wallets

### ISSUE THREAD

**Issue by luandro** [bochaco/safe-coins-wallet#1]
Hey @bochaco, thanks for this. We're trying to use this lib to reproduce a wallet. We've managed to use some functions:

```
        const wallet = await safeCoinsWallet.createWallet(state.appHandle, input)
        const inbox = await safeCoinsWallet.createTxInbox(state.appHandle, input)
        const walletCoins = await safeCoinsWallet.loadWalletData(state.appHandle, wallet)
```

But how can I retrieve wallet data when we're not creating a new wallet? Where are public and private keys stored?

Thanks, cheers!

**Comment by bochaco** [comment]
Hi @luandro , nice to hear you are using it!
The value returned by `createWallet` is the serialised private MutableData info which contains everything needed to retrieve the data stored in it, including the encryption keys, that's why you are able to call `loadWalletData` with it. If you keep a copy of the value you received from `createWallet` you can use it anytime later on with `loadWalletData` again. I hope that's what you are asking.

**Comment by bochaco** [comment]
I just added a brief description and explanation for each of the API functions to the README, I hope that also helps.

**Comment by luandro** [comment]
Thanks for the descriptions in the `README.md`, makes the API  and the workings clearer.

When I create a new wallet a get a serialized number: `34,202,165,206,167,176,71,19,74...`. Should I manually store it in a users private data some where to get hold of this wallet again later? Or is this storing already taken care some how?

**Comment by bochaco** [comment]
Correct, you need to store that to then be able to retrieve the coin wallet, it is the app's decision/design where to store it. Remember that the wallet is a private MutableData with all its content being encrypted, so you need to have the address and the encryption/decryption keys to be able to access it and read/write it, this is exactly what the function returns in a serialised form.

**Comment by luandro** [comment]
Thanks, that already answers my question. But I'm not sure how to implement such a function. Here's my first take:

```js
const wallet = await createWallet(...)
const serviceHash = await genXorName(appHandle, 'wallet')
const mdHandle = await window.safeMutableData.newPublic(appHandle, serviceHash, typeTag)
await window.safeMutableData.quickSetup(mdHandle, { currentWallet: wallet }, name, description)
```

So that later I can just get the serialized data again. Would this be enough, or am I leaking important private information?

**Comment by bochaco** [comment]
Yes you would be leaking all the information to access and decrypt the wallet.
You'll need to store it encrypted in a private MutableData, one that you create at either a specific location or at a random location; or you could store it in the app's own container as well, which internally is also a private MutableData.

**Comment by luandro** [comment]
Got it, thank you very much for the work! 👍
